// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ScribbleCodeGenConsole")>]
[<assembly: AssemblyProductAttribute("ScribbleCodeGen")>]
[<assembly: AssemblyDescriptionAttribute("Generate F# Files from Scribble output")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ScribbleCodeGenConsole"
    let [<Literal>] AssemblyProduct = "ScribbleCodeGen"
    let [<Literal>] AssemblyDescription = "Generate F# Files from Scribble output"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
